name: On Pull Request

on:
  pull_request:
    branches: [v2.11.2-patched]

jobs:
  test:
    name: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Layer Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.event.number }}
          restore-keys: ${{ runner.os }}-docker-

      # Buildx Needs QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # We use Buildx so we can take advantage of the caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/${{ github.repository }}:PR${{ github.event.number }}
          push: true
